name: JSON check

on:
  pull_request:

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
          
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: andrew
        if: github.repository_owner == 'github.actor'
        uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.BOT }}"
        
          
      - name: blue
        if: ${{ BLUE }} == 'github.actor'
        uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.BOT }}"
        env:
          BLUE: 'blueedgetechno'
  
  run-if-fail:
    if: ${{ always() && (needs.json.result=='failure') }}
    needs: [json]
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      uses: unofficial-skills/actions-comment-pull-request@main
      with:
         message: |
              ❌ Storing the JSON file has failed due to verification issues
         GITHUB_TOKEN: ${{ secrets.BOT }}
