name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:  

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open 10 days with no activity. Remove the stale label or comment (the label will be removed after the next run of the workflow), or this will be closed in 5 days of further inactivity.'
          stale-pr-message: 'This PR is stale because it has been open 15 days with no activity. Remove the stale label or comment (the label will be removed after the next run of the workflow), or this will be closed in 10 days of further inactivity.'
          close-issue-message: 'This issue was closed because it has been stale for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 10 days with no activity.'
          days-before-issue-stale: 10
          days-before-pr-stale: 15
          days-before-issue-close: 5
          days-before-pr-close: 10
          repo-token: ${{ secrets.BOT }}
